/**
 * @fileoverview gRPC-Web generated client stub for proto
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v4.25.3
// source: greet.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.proto = require('./greet_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.proto.ProtocServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.proto.ProtocServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.proto.GreetRequest,
 *   !proto.proto.GreetResponse>}
 */
const methodDescriptor_ProtocService_Greet = new grpc.web.MethodDescriptor(
  '/proto.ProtocService/Greet',
  grpc.web.MethodType.UNARY,
  proto.proto.GreetRequest,
  proto.proto.GreetResponse,
  /**
   * @param {!proto.proto.GreetRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.proto.GreetResponse.deserializeBinary
);


/**
 * @param {!proto.proto.GreetRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.proto.GreetResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.proto.GreetResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.proto.ProtocServiceClient.prototype.greet =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/proto.ProtocService/Greet',
      request,
      metadata || {},
      methodDescriptor_ProtocService_Greet,
      callback);
};


/**
 * @param {!proto.proto.GreetRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.proto.GreetResponse>}
 *     Promise that resolves to the response
 */
proto.proto.ProtocServicePromiseClient.prototype.greet =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/proto.ProtocService/Greet',
      request,
      metadata || {},
      methodDescriptor_ProtocService_Greet);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.proto.ServerStreamGreetRequest,
 *   !proto.proto.ServerStreamGreetResponse>}
 */
const methodDescriptor_ProtocService_GreetServerStream = new grpc.web.MethodDescriptor(
  '/proto.ProtocService/GreetServerStream',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.proto.ServerStreamGreetRequest,
  proto.proto.ServerStreamGreetResponse,
  /**
   * @param {!proto.proto.ServerStreamGreetRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.proto.ServerStreamGreetResponse.deserializeBinary
);


/**
 * @param {!proto.proto.ServerStreamGreetRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.proto.ServerStreamGreetResponse>}
 *     The XHR Node Readable Stream
 */
proto.proto.ProtocServiceClient.prototype.greetServerStream =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/proto.ProtocService/GreetServerStream',
      request,
      metadata || {},
      methodDescriptor_ProtocService_GreetServerStream);
};


/**
 * @param {!proto.proto.ServerStreamGreetRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.proto.ServerStreamGreetResponse>}
 *     The XHR Node Readable Stream
 */
proto.proto.ProtocServicePromiseClient.prototype.greetServerStream =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/proto.ProtocService/GreetServerStream',
      request,
      metadata || {},
      methodDescriptor_ProtocService_GreetServerStream);
};


module.exports = proto.proto;

